[build]
  command = "node node_modules/vite/bin/vite.js build"
  publish = "dist"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200